name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install system dependencies
      run: sudo apt-get update && sudo apt-get install -y libpango1.0-dev

    - name: Set PKG_CONFIG_PATH
      run: echo "/usr/lib/x86_64-linux-gnu/pkgconfig" >> $GITHUB_ENV

    - name: Build
      run: cd napture && cargo build --verbose

    - name: Run tests
      run: cd napture && cargo test --verbose
