name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: "Build Napture"
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: |
        echo "Installing dependencies..."
        sudo apt-get update
        sudo apt-get install -y libglib2.0-dev libcairo2-dev libgraphene-1.0-dev libgtk-4-dev libadwaita-1-dev 
        sudo add-apt-repository universe
        sudo apt install libfuse2
        echo "Dependencies installed."

    - name: Build Napture
      run: |
        echo "Building Napture..."
        cd napture
        export PKG_CONFIG_PATH=/usr/lib/pkgconfig
        cargo build --release
        echo "Napture built successfully."
    - name: Install AppImageTool
      run: |
        echo "Starting artifact upload phase..."
        echo "Installing AppImageTool..."
        wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
        chmod +x appimagetool-x86_64.AppImage
        echo "AppImageTool installed."
    #DEBUGGING: LIST FILES TO FIND THE APPIMAGE.
    - name: Create Napture AppImage
      run: |
        echo "Creating Napture AppImage..."
        cd napture
        mkdir -p AppDir/usr/bin
        cp target/release/webx AppDir/usr/bin/
        cp io.github.face_hh.Napture.desktop AppDir/
        cp io.github.face_hh.Napture.svg AppDir/
        ARCH=x86_64
         ../appimagetool-x86_64.AppImage AppDir
        mv Napture-x86_64.AppImage ../Bussin.Napture-x86_64.AppImage
        echo "AppImage created successfully."
    - name: Rename AppImage
      run: |
        echo "Renaming AppImage..."
        mv Bussin.Napture-x86_64.AppImage napture-v${{ github.sha }}.AppImage
        echo "AppImage renamed successfully."

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: napture-v${{ github.sha }}.AppImage
        path: napture-v${{ github.sha }}.AppImage
      env:
        UPLOAD_URL: ${{ steps.upload.outputs.upload_url }}
  upload:
   name: "Upload Release"
   runs-on: ubuntu-24.04
   needs:
      - build
   steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4.1.7
        with:
          name: napture-v${{ github.sha }}.AppImage
      - name: Publish AppImage to Releases
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            wget -q https://github.com/TheAssassin/pyuploadtool/releases/download/continuous/pyuploadtool-x86_64.AppImage
            chmod +x pyuploadtool-x86_64.AppImage
            ./pyuploadtool-x86_64.AppImage napture-v${{ github.sha }}.AppImage*
