name: Rust

on:
  push:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build Napture (Ubuntu)
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: |
        echo "Installing dependencies..."
        sudo apt-get update
        sudo apt-get install -y libglib2.0-dev libcairo2-dev libgraphene-1.0-dev libgtk-4-dev libadwaita-1-dev 
        sudo add-apt-repository universe
        sudo apt install libfuse2
        echo "Dependencies installed."

    - name: Build Napture
      run: |
        echo "Building Napture..."
        cd napture
        export PKG_CONFIG_PATH=/usr/lib/pkgconfig
        cargo build --release
        echo "Napture built successfully."
    - name: Install linuxdeploy
      run: |
        echo "Starting artifact upload phase..."
        echo "Installing linuxdeploy..."
        wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
        chmod +x linuxdeploy-x86_64.AppImage
        echo "linuxdeploy installed."
    - name: Create Napture AppImage
      run: |
        echo "Creating Napture AppImage..."
        cd napture
        mv target/release/webx target/release/napture
        ARCH=x86_64
         ../linuxdeploy-x86_64.AppImage --appdir AppDir -e target/release/napture -d io.github.face_hh.Napture.desktop -i io.github.face_hh.Napture.svg -o appimage
        mv Napture-x86_64.AppImage ../Bussin.Napture-x86_64.AppImage
        echo "AppImage created successfully."
    - name: Rename AppImage
      run: |
        echo "Renaming AppImage..."
        mv Bussin.Napture-x86_64.AppImage napture-v${{ github.sha }}.AppImage
        echo "AppImage renamed successfully."

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: napture-v${{ github.sha }}.AppImage
        path: napture-v${{ github.sha }}.AppImage
      env:
        UPLOAD_URL: ${{ steps.upload.outputs.upload_url }}  
        
  build_win:
    name: Build Napture (Windows)
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
  
    - name: Install Dependencies
      run: |
        echo "Installing dependencies..."
        choco install -y gtk-runtime
        rustup toolchain install stable-gnu && rustup default stable-gnu
        echo "Dependencies installed."

    - name: Install MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msys2-root: 'C:\msys64'
        install-dir: 'C:\msys64'
    
    - name: Install MSYS2 dependencies
      shell: msys2 {0}
      run: |
        echo "Installing MSYS2 packages..."
        pacman --noconfirm -S mingw-w64-x86_64-toolchain base-devel mingw-w64-x86_64-gtk4 mingw-w64-x86_64-gettext mingw-w64-x86_64-libxml2 mingw-w64-x86_64-librsvg mingw-w64-x86_64-pkgconf mingw-w64-x86_64-gcc mingw-w64-x86_64-libadwaita mingw-w64-x86_64-lua mingw-w64-x86_64-pkg-config

    - name: Set PATH
      shell: powershell
      run: |
        echo "C:\msys64\mingw64\bin" | Out-File -FilePath $env:GITHUB_PATH -Append
        echo "C:\msys64\usr\bin" | Out-File -FilePath $env:GITHUB_PATH -Append
        echo "C:\msys64\mingw64\include" | Out-File -FilePath $env:GITHUB_PATH -Append
        echo "C:\msys64\mingw64\lib" | Out-File -FilePath $env:GITHUB_PATH -Append
        echo "PATH is now: $env:Path"

    - name: Build Napture
      run: |
        echo "Building Napture..."
        pkg-config --help
        cd napture
        cargo build --release
        echo "Napture built successfully."

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: napture-v${{ github.sha }}.exe
        path: napture/target/release/webx.exe

  upload:
   name: "Upload Release"
   runs-on: ubuntu-24.04
   needs:
      - build
      - build_win
   steps:
      - name: Download Ubuntu Artifact
        uses: actions/download-artifact@v4.1.7
        with:
          name: napture-v${{ github.sha }}.AppImage
          # Windows is still a WIP.
      - name: Download Windows Artifact
        uses: actions/download-artifact@v2
        with:
          name: napture-v${{ github.sha }}.exe
      - name: Download Dependencies
        run: |
            sudo add-apt-repository universe
            sudo apt install libfuse2
      - name: Publish AppImage to Releases
        uses: softprops/action-gh-release@v2.0.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          token: ${{ env.GITHUB_TOKEN }}
          files: |
            napture-v${{ github.sha }}.AppImage
            napture-v${{ github.sha }}.exe
          prerelease: true
