name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
        libpango1.0-dev \
        software-properties-common
        sudo dpkg --add-architecture i386
        sudo add-apt-repository 'deb http://deb.debian.org/debian sid main'
        sudo apt-get update
        sudo apt-get install -y \
        libgtk-4-dev \
        libgtk-4-1


    - name: Build
      run: |
        cd napture
        export PKG_CONFIG_PATH=/usr/lib/pkgconfig
        cargo build --verbose
    - name: Run tests
      run: |
        cd napture 
        cargo test --verbose
