name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Add PPA for GTK4
      run: |
        sudo apt-get update
        sudo apt-get install -y software-properties-common
        sudo add-apt-repository ppa:gnome3-team/gnome3-staging
        sudo apt-get update
    - name: Install dependencies
      run: sudo apt-get install -y libgtk-4-dev
    - name: Build
      run: cd napture && cargo build --verbose
    - name: Run tests
      run: cd napture && cargo test --verbose
