name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
#curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y FUCK
jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies and Rustup
      run: |
        echo "Installing dependencies and Rustup..."
        sudo apt-get update
        sudo apt-get install -y libglib2.0-dev libcairo2-dev libgraphene-1.0-dev libgtk-4-dev libadwaita-1-dev liblua5.4-dev
        echo "Dependencies and Rustup installed."

    - name: Build and Install Napture
      run: |
        echo "Building Napture..."
        cd napture
        export PKG_CONFIG_PATH=/usr/lib/pkgconfig
        cargo build --verbose
        echo "Napture built successfully."

