name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: |
        echo "Installing dependencies..."
        sudo apt-get update
        sudo apt-get install -y libglib2.0-dev libcairo2-dev libgraphene-1.0-dev libgtk-4-dev libadwaita-1-dev 
        echo "Dependencies installed."

    - name: Build Napture
      run: |
        echo "Building Napture..."
        cd napture
        export PKG_CONFIG_PATH=/usr/lib/pkgconfig
        cargo build --release
        echo "Napture built successfully."
    - name: Install AppImageTool
      run: |
        echo "Installing AppImageTool..."
        wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
        chmod +x appimagetool-x86_64.AppImage
        echo "AppImageTool installed."
    - name: Create Napture AppImage
      run: |
        echo "Creating Napture AppImage..."
        cd napture
        mkdir -p AppDir/usr/bin
        cp target/release/webx AppDir/usr/bin/
        cp io.github.face_hh.Napture.desktop AppDir/
        cp io.github.face_hh.Napture.svg AppDir/
        ARCH=x86_64
        APPIMAGETOOL_APP_NAME="Bussin.Napture-x86_64"
         ../appimagetool-x86_64.AppImage AppDir --appimage-extract
        mv Bussin.Napture-x86_64.AppImage ../Bussin.Napture-x86_64.AppImage
        echo "AppImage created successfully."
    - name: Publish AppImage to Releases
      uses: actions/upload-artifact@v4.3.3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        path: Bussin.Napture-x86_64.AppImage
        name: Bussin.Napture-x86_64.AppImage
