name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: |
        echo "Installing dependencies..."
        sudo apt-get update
        sudo apt-get install -y libglib2.0-dev libcairo2-dev libgraphene-1.0-dev libgtk-4-dev libadwaita-1-dev 
        echo "Dependencies installed."

    - name: Build Napture
      run: |
        echo "Building Napture..."
        cd napture
        export PKG_CONFIG_PATH=/usr/lib/pkgconfig
        cargo build --release
        echo "Napture built successfully."
    - name: Install AppImageTool
      run: |
        echo "Installing AppImageTool..."
        wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
        chmod +x appimagetool-x86_64.AppImage
        echo "AppImageTool installed."
    - name: Create Napture AppImage
      run: |
        echo "Creating Napture AppImage..."
        cd napture
        mkdir -p AppDir/usr/bin
        cp -r target/release/ AppDir/usr/bin/
        cp ../webx-github-actions/napture/io.github.face_hh.Napture.desktop AppDir/
        cp ../webx-github-actions/napture/io.github.face_hh.Napture.svg AppDir/
        ./appimagetool-x86_64.AppImage AppDir
        echo "AppImage created successfully."
    - name: Publish AppImage to Releases
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: napture-x86_64.AppImage
        asset_name: napture-x86_64.AppImage
        asset_content_type: application/octet-stream
